// The design tokens (src/styles/tokens.css) come unchanged from the design
// handoff: light on :root, dark on [data-ms-theme="dark"] (set by the theme
// switch). Without a stored choice, and without JavaScript, the site follows
// the system setting: this derives that rule from the dark block, so the
// colour values exist only once.

const DARK_BLOCK = /\[data-ms-theme="dark"\]\s*\{([^{}]*)\}/;

export function systemThemeCss(tokens: string): string {
	const match = DARK_BLOCK.exec(tokens);
	if (!match?.[1]?.includes('--ms-')) throw new Error('tokens.css: no [data-ms-theme="dark"] block with --ms-* tokens');
	return (
		'/* Generated by scripts/assets.ts from src/styles/tokens.css - do not edit. */\n' +
		"@media (prefers-color-scheme: dark) {\n\t:root:not([data-ms-theme='light']) {" +
		match[1] +
		'}\n}\n'
	);
}
