// Generated assets that are not Svelte pages. Runs after scripts/import-spec.ts
// (which recreates .generated/static):
//   .generated/theme-system.css   system dark theme, derived from tokens.css
//   .generated/static/js/*.js     browser scripts from src/client/ (content pages
//                                 ship no SvelteKit runtime, see +layout.ts)
//   src/lib/generated/client.ts   their published paths, for <script src>
// Run with: node scripts/assets.ts
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { build, type Rollup } from 'vite';
import { systemThemeCss } from './lib/tokens.ts';

const ROOT = new URL('..', import.meta.url).pathname;
const OUT = join(ROOT, '.generated', 'static', 'js');

// Classic script, loaded synchronously in <head>.
const BOOT = { themeBoot: 'src/client/theme-boot.ts' };
// ES modules (deferred by nature), one per kind of page.
const MODULES: Record<string, string> = {
	site: 'src/client/site.ts'
};

function entries(output: Rollup.RollupOutput | Rollup.RollupOutput[] | unknown): Record<string, string> {
	const outputs = (Array.isArray(output) ? output : [output]) as Rollup.RollupOutput[];
	const files: Record<string, string> = {};
	for (const chunk of outputs.flatMap((o) => o.output)) {
		if (chunk.type === 'chunk' && chunk.isEntry) files[chunk.name] = `/js/${chunk.fileName}`;
	}
	return files;
}

async function bundle(input: Record<string, string>, format: 'iife' | 'es', empty: boolean): Promise<Record<string, string>> {
	const result = await build({
		configFile: false,
		root: ROOT,
		publicDir: false,
		logLevel: 'warn',
		build: {
			outDir: OUT,
			emptyOutDir: empty,
			target: 'es2022',
			sourcemap: false,
			modulePreload: false,
			rollupOptions: {
				input: Object.fromEntries(Object.entries(input).map(([name, file]) => [name, join(ROOT, file)])),
				output: { format, entryFileNames: '[name].[hash].js', chunkFileNames: '[name].[hash].js' }
			}
		}
	});
	return entries(result);
}

writeFileSync(join(ROOT, '.generated', 'theme-system.css'), systemThemeCss(readFileSync(join(ROOT, 'src', 'styles', 'tokens.css'), 'utf8')));

const scripts = { ...(await bundle(BOOT, 'iife', true)), ...(await bundle(MODULES, 'es', false)) };
mkdirSync(join(ROOT, 'src', 'lib', 'generated'), { recursive: true });
writeFileSync(
	join(ROOT, 'src', 'lib', 'generated', 'client.ts'),
	`// Generated by scripts/assets.ts - do not edit.\nexport const scripts = ${JSON.stringify(scripts, null, '\t')} as const;\n`
);
console.log(`Client scripts: ${Object.values(scripts).join(', ')}`);
