// Discovers the language packs under languages/<tag>/ (meta.json,
// messages.json and pages/*.json with the texts of one page each), validates them and generates
// everything that depends on the list of languages:
//   .generated/messages/<tag>.json   messages, missing keys filled from English
//   project.inlang/settings.json     inlang project for Paraglide
//   src/lib/paraglide/               compiled message functions (Paraglide)
//   src/lib/generated/languages.ts   list for the language menu, hreflang, prerendering
//   .generated/languages.json        the same list for svelte.config.js
// Adding a language never needs a code change: add languages/<tag>/ and open a PR.
// Run with: node scripts/languages.ts
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { compile } from '@inlang/paraglide-js';
import {
	checkMessages,
	combineFiles,
	coverage,
	isLanguageTag,
	mergeWithBase,
	parseMeta,
	type LanguageMeta,
	type PackFile
} from './lib/languages.ts';

const ROOT = new URL('..', import.meta.url).pathname;
const LANGUAGES = join(ROOT, 'languages');
const BASE = 'en';

interface Language extends LanguageMeta {
	tag: string;
	complete: boolean;
	coverage: number;
}

function readJson(path: string): unknown {
	return JSON.parse(readFileSync(path, 'utf8'));
}

/** messages.json plus pages/*.json (texts of one page each), in a stable order. */
function readPack(dir: string): PackFile[] {
	const files: PackFile[] = [{ name: 'messages.json', content: readJson(join(dir, 'messages.json')) }];
	const pages = join(dir, 'pages');
	if (existsSync(pages)) {
		for (const name of readdirSync(pages).filter((n) => n.endsWith('.json')).sort()) {
			files.push({ name: `pages/${name}`, content: readJson(join(pages, name)) });
		}
	}
	return files;
}

function main(): void {
	const errors: string[] = [];
	const tags = readdirSync(LANGUAGES, { withFileTypes: true })
		.filter((entry) => entry.isDirectory())
		.map((entry) => entry.name)
		.sort((a, b) => (a === BASE ? -1 : b === BASE ? 1 : a.localeCompare(b)));
	if (!tags.includes(BASE)) throw new Error(`languages/${BASE} is required`);

	const baseCombined = combineFiles(BASE, readPack(join(LANGUAGES, BASE)));
	errors.push(...baseCombined.errors);
	const base = baseCombined.messages;
	const languages: Language[] = [];
	const merged: Record<string, Record<string, unknown>> = {};

	for (const tag of tags) {
		if (!isLanguageTag(tag)) {
			errors.push(`languages/${tag}: not a BCP 47 language tag like "de" or "pt-BR"`);
			continue;
		}
		let meta: LanguageMeta;
		let messages: Record<string, unknown>;
		try {
			meta = parseMeta(readJson(join(LANGUAGES, tag, 'meta.json')));
			const combined = combineFiles(tag, readPack(join(LANGUAGES, tag)));
			errors.push(...combined.errors);
			messages = combined.messages;
		} catch (e) {
			errors.push(`languages/${tag}: ${(e as Error).message}`);
			continue;
		}
		const check = checkMessages(tag, base, messages);
		errors.push(...check.errors);
		if (check.missing.length > 0) {
			console.log(`languages/${tag}: ${check.missing.length} key(s) fall back to English`);
		}
		languages.push({ tag, ...meta, complete: check.missing.length === 0, coverage: coverage(base, messages) });
		merged[tag] = mergeWithBase(base, messages);
	}

	if (errors.length > 0) {
		console.error(errors.map((e) => `  ${e}`).join('\n'));
		console.error(`\n${errors.length} problem(s) in the language packs. See TRANSLATING.md.`);
		process.exit(1);
	}

	const generated = join(ROOT, '.generated', 'messages');
	rmSync(generated, { recursive: true, force: true });
	mkdirSync(generated, { recursive: true });
	for (const [tag, messages] of Object.entries(merged)) {
		writeFileSync(join(generated, `${tag}.json`), `${JSON.stringify(messages, null, 2)}\n`);
	}

	mkdirSync(join(ROOT, 'project.inlang'), { recursive: true });
	writeFileSync(
		join(ROOT, 'project.inlang', 'settings.json'),
		`${JSON.stringify(
			{
				$schema: 'https://inlang.com/schema/project-settings',
				baseLocale: BASE,
				locales: languages.map((l) => l.tag),
				modules: ['./node_modules/@inlang/plugin-icu1/dist/index.js'],
				'plugin.inlang.icu-messageformat-1': { pathPattern: './.generated/messages/{locale}.json' }
			},
			null,
			2
		)}\n`
	);

	mkdirSync(join(ROOT, 'src', 'lib', 'generated'), { recursive: true });
	writeFileSync(
		join(ROOT, 'src', 'lib', 'generated', 'languages.ts'),
		`// Generated by scripts/languages.ts - do not edit.\n` +
			`export interface Language { tag: string; name: string; dir: 'ltr' | 'rtl'; translators: string[]; complete: boolean; coverage: number }\n` +
			`export const languages: Language[] = ${JSON.stringify(languages, null, '\t')};\n`
	);
	writeFileSync(join(ROOT, '.generated', 'languages.json'), `${JSON.stringify(languages, null, 2)}\n`);
	console.log(`Languages: ${languages.map((l) => (l.complete ? l.tag : `${l.tag} (partial)`)).join(', ')}`);
}

main();
await compile({
	project: join(ROOT, 'project.inlang'),
	outdir: join(ROOT, 'src', 'lib', 'paraglide'),
	strategy: ['url', 'baseLocale'],
	emitGitIgnore: false
});
